parameters:

services:

    app_kernel_listener:
        class:  AppBundle\Listener\KernelListener
        tags:  [{ name: kernel.event_subscriber }]
        arguments: ['%secure_routes%']
        calls:
            - [setContainer,        ['@service_container']]
            - [setRouteServices,    ['@router','@request_stack']]
            - [setSecurityServices, ['@security.token_storage','@security.authorization_checker','@security.authentication_utils']]

    common_abstract_action:
        abstract: true
        calls:
            - [setContainer,        ['@service_container']]
            - [setRouteServices,    ['@router','@request_stack']]
            - [setSecurityServices, ['@security.token_storage','@security.authorization_checker','@security.authentication_utils']]
    # Index
    app_index_action:
        class:  AppBundle\Module\App\Index\IndexAction
        parent: common_abstract_action

    # Welcome
    app_welcome_action:
        class:  AppBundle\Module\App\Welcome\WelcomeAction
        parent: common_abstract_action
